/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fishz' at '10/24/15 6:49 AM' with Gradle 2.5
 *
 * @author fishz, @date 10/24/15 6:49 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
